version: "3.3"

services:

  web:
    container_name: springapiejemplo
    image: .
    volumes:
      - ./mysql:/var/lib/musql
    ports:
      - "8001:8000"
    command: sleep infinity

  #MariaDB
  db:
    container_name: mariadb_laravel
    image: docker.io/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: laravel
      MARIADB_USER: usuario
      MARIADB_PASSWORD: usuario1234
    volumes:
      - ./mariadb:/var/lib/mysql
